### ISSUE TITLE
compilation fixes

### ISSUE THREAD

**Issue by nmhancock** [openfaas-incubator/faas-memory#11]
Hey all, I noticed this doesn't compile anymore or work with go modules.

I made a new repo from scratch so the go modules would be fixed, and then edited handlers/info.go for updates in the following types:
    typesv1.ProviderInfo
    typesv1.VersionInfo

My code is over here: https://github.com/nmhancock/faas-memory-mod
Feel free to take it and do whatever, I found this useful as a reference.

@alexellis <3

**Comment by alexellis** [comment]
Hi Nicholas, what's the plan with faas-memory?

We can find someone to update the project or did you want to send your own PR?

Alex
