### ISSUE TITLE
Update faas-provider to 0.13.3

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/faas-memory#6]
This repo acts as an example and should use the latest faas-provider to 0.13.3 version, it will need a change in the proxy and also need a namespaces endpoint.

Here's a simple example that implements the proxy:

https://github.com/alexellis/faas-containerd/

* Update Gopkg.toml
* Run `dep ensure`
* Update the main/server.go adding namespaces / updating the proxy code to add a lookup struct
* Anything else

**Comment by alexellis** [comment]
We had the wrong filename `.DEREK.yaml` not `.DEREK.yml`, updated that now, you can re-assign in about 5 mins.

**Comment by Waterdrips** [comment]
/close
this has been upgraded to 0.14.0
